---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure availability of base packages
  apt: name={{ item }} state=present
  with_items:
    - cowsay
    - curl
    - figlet
    - git
    - git-svn
    - htop
    - jq
    - maven
    - netcat-openbsd
    - openjdk-7-jdk
    - realpath
    - subversion
    - tmux
    - tree
    - unattended-upgrades
    - wget
    - zsh

- name: Enable vim as default editor
  command: /usr/bin/update-alternatives --set editor /usr/bin/vim.basic

- name: Add cron for unattended-upgrades after reboot
  cron: state=present job=/usr/bin/unattended-upgrades name='Upgrades after Reboot' reboot=yes

- name: Add cron for unattended-upgrades regularly
  cron: state=present job=/usr/bin/unattended-upgrades name='Regular upgrades' hour=11 minute=0

- include: docker.yml