---
- name: Ensure availability of PHP packages
  apt: name={{ item }} state=present
  with_items:
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-imap
    - php-intl
    - php-ldap
    - php-json
    - php-mcrypt
    - php-mysql
    - php-pgsql
    - php-xdebug
    - php-xsl

