---
- name: Ensure availability of PHP packages
  apt: name={{ item }} state=present
  with_items:
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imap
    - php5-intl
    - php5-ldap
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-pgsql
    - php5-sqlite
    - php5-xdebug
    - php5-xsl

