---
- name: Ensure availability of PHP packages
  apt: name={{ item }} state=present
  with_items:
    - php7.0-cli
    - php7.0-curl
    - php7.0-gd
    - php7.0-imap
    - php7.0-intl
    - php7.0-json
    - php7.0-ldap
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-pgsql
    - php7.0-sqlite3
    - php7.0-xsl
    - php7.0-zip

