---
- name: Ensure availability of personal user
  user: name="{{ host_user }}" shell="{{ host_user_shell }}" groups=sudo state=present

- name: Ensure availability of personal SSH key(s) for personal user
  authorized_key: user="{{ item }}" key="{{ host_user_ssh_key }}"
  with_items:
    - "{{ host_user }}"
    - vagrant
    - root

- name: Ensure registration of personal user as passwordless root-sudoer
  template: dest="/etc/sudoers.d/{{ host_user }}" src=sudoers.j2 validate='visudo -cf %s' owner=root group=root

- name: Provision user to Samba
  shell: "(echo;echo) | /usr/bin/smbpasswd -a {{ host_user }} -s && touch /etc/samba/user-{{ host_user }}.provisioned"
  args:
    creates: "/etc/samba/user-{{ host_user }}.provisioned"
  notify:
    - restart samba