---
- name: Ensure Samba being installed
  apt: name={{item}} state=present
  with_items:
    - samba 
    - smbclient

- name: Provide Samba service configuration
  copy: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root

- name: Ensure smbd running
  service: name=smbd state=started

- name: Ensure nmbd running
  service: name=nmbd state=started
